//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinoRestaurant.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string DeletedBy { get; set; }
        public string DeletedOn { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
